### ISSUE TITLE
permission error since last update 24/06/2018

### ISSUE THREAD

**Issue by slcb** [linuxserver/docker-mcmyadmin2#13]
since the update to v87, I get permission errors on a deployment that has worked fine before. My user (set via PUID/PGID) has access (0775) to the relevant path.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Debian Openmediavault 4

![screen shot 2018-06-27 at 11 55 44](https://user-images.githubusercontent.com/22263338/41963758-0f1b5eee-7a01-11e8-9383-7eaacdc0a49f.png)

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1007
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing... 
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
[services.d] done.
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied
s6-applyuidgid: fatal: unable to exec ./MCMA2_Linux_x86_64: Permission denied

/var/docker is symlinked to another location; has worked fine before update
config directory is directly accessed

**Comment by thelamer** [comment]
I cannot duplicate this, make sure the directory you have the /minetest folder mounted to is woend by 1007:100 . Alternatively this issue is quite old this could have been an issue with a specific release. Please pull latest and try again.

**Comment by thelamer** [comment]
I actually can reproduce this, sorry for the false close, it looks like during init the forked mcmyadmin force exits the script so the actual chown command would not be run until the container restarts. 

Essentially as is this container has been in a broken state for some time. I am discussing our options with the team as it looks like this bin was never really designed to be run in environments outside of "screen". The consoleless commands do not seem to work anymore which leads to a lot of manual setup in the config file.

**Comment by homerr** [comment]
I'm afraid to announce we have deprecated this image due to the nature of how the binary is distributed, and the fact we are unable to make it work as intended. I hope you understand, and find another way to run this in the future.
