### ISSUE TITLE
Server cant restart + autostarts while starting the docker container

### ISSUE THREAD

**Issue by Joly0** [linuxserver/docker-mcmyadmin2#14]
So first, i am running the docker container on my synology nas and i have the problem, when i try to stop the Server, either by clicking on stop or entering the stop command, the server stops and imediatly restarts.

The second thing that grinds my gears is, that the server starts directly, after i start the docker container and i dont want this. Normally McMyAdmin has an option to disable autostart of the server by adding -nostart to the .cmd .bat or .sh file but it seems to not work for this docker container what is really sad, because sometimes i just want to start the container and change some settings and start the server after, but atm together with the first bug, i cant even do this really good.

Hopefully you are able to do something against this.

thank you

**Comment by homerr** [comment]
All of our containers are designed so that when the actual container itself is started, the services within will also come up. This is not something we will be changing - if you don't want the services to come up don't start the container? Could I ask why this is of importance?

Much the same with stopping/starting the servicethrough the webui, the containers service manager will detect the service has died and then start it again. The only way you can stop/restart the service is by restarting the container.

**Comment by Joly0** [comment]
Well, as i already pointed out, often i just want to start the container, change some settings for testing and then start the server itself, and with the method at the moment, i first have to wait for it to fully load (what can take extremly long, if you add plenty mods to your server) and then shut it down and even then, because of the second problem, it automatically restarts. If i wanted to edit the configs, without the container active, i could use a regular docker container, that simply starts the server itself, without the webinterface, because, what is a webinterface for, if you have to restart either the server or the container, everytime you edit even a single thing.

Btw, if this describes the problem i have in a way, that you understand it and agree with it, a simple fix for both problems would be, to just add screen to the apt install part and start mcmyadmin in screen and also add -nostart after all the other commands (-configonly, -setpw, etc.). 

And even if u dont want to directly integrate the -nostart command, maybe its possible to add it as a configurable startup argument, so you can decide by yourself, if you want to start both or just start one.

**Comment by thelamer** [comment]
@Joly0 I can definitively say we will not be implementing this. I know it does not line up with your use case, but Env variables to determine if we want to start a service or not is not a rabbit hole we will be going down. 
I need to do some other work on this repo to get it compatible with our build system, like the default password change etc, but I can say that we will not be implementing this kind of logic. 
If you are a power user I highly recommend pulling this git repo and building the docker image locally with the https://github.com/linuxserver/docker-mcmyadmin2/blob/master/root/etc/services.d/mcmyadmin2/run file modified to suit your needs.
