### ISSUE TITLE
Default Password Not Allowed

### ISSUE THREAD

**Issue by selkiess** [linuxserver/docker-mcmyadmin2#15]
McMyAdmin2 no longer allows the default password to be used. Current versions refuse to allow anyone to log in as long as the default password is set.

**Comment by Drizztfire** [comment]
Hi,
Quick workaround : 
Shutdown the container
Go edit mcmyadmin.conf and change Security.RequirePasswordChange=True to False
Start the container and go change your password

**Comment by homerr** [comment]
I'm afraid to announce we have deprecated this image due to the nature of how the binary is distributed, and the fact we are unable to make it work as intended. I hope you understand, and find another way to run this in the future.
