### ISSUE TITLE
Upgrade to McMyAdmin3 or New Docker For It

### ISSUE THREAD

**Issue by selkiess** [linuxserver/docker-mcmyadmin2#16]
McMyAdmin2 is no longer being actively developed and is mostly on bugfixes only. McMyAdmin3/[AMP](https://cubecoders.com/AMP) is now the current version being actively updated.

AMP is actually being actively developed and brings with it improvements to the minecraft module such as being able to automatically install modded minecraft servers and an updated and streamlined UI.

**Comment by spencerskinner99** [comment]
Yeh I'd also like to see AMP as it has support for more than just Minecraft now, would be brilliant to see!

**Comment by j0nnymoe** [comment]
This is something we currently have no plans for.

**Comment by spencerskinner99** [comment]
That's fair, I think it's still in beta to be fair and has been for a long time, I don't know what the development is actually like on it. Would be a waste for you guys to develop a container for a poorly supported hosting software ahaha. Thanks for the update though, most appreciated!
