### ISSUE TITLE
Installing Spigot

### ISSUE THREAD

**Issue by ghostsquad** [linuxserver/docker-mcmyadmin2#3]
I noticed several comments and such about Spigot being removed. Why was that?

It would be nice at the very least to have that installed or as part of the dockerfile so that it's easy to start a Spigot server if necessary.

Another nice to have would be Forge.

**Comment by lonix** [comment]
I Am not ignoring this question, im just delaying answering it, to figgure out how to answer you properly

**Comment by ghostsquad** [comment]
That's ok. Just a question. If there is some technical reason for not including it, that would be nice to know. Otherwise, I was thinking of forking this and adding Spigot support.

**Comment by lonix** [comment]
Im sorry this took me a while. But this will be returning later with the release of Mcmyadmin version 3 The issue is the The version numberings is not static-ly linked like they used to be. (You can still complie the files and add them yourself :)
