### ISSUE TITLE
MCMyAdmin3

### ISSUE THREAD

**Issue by Bril0** [linuxserver/docker-mcmyadmin2#4]
Hey just a quick thanks for the container work and wanted to ask if you would be planning to make a container for AMP which is the new MCMyAdmin3? It's in beta but does allow automatic spigot and craftbukkit installation. Thanks again

**Comment by lonix** [comment]
Whenever its available to the general public i will probably release one :).

(i have something running privatly).

**Comment by Bril0** [comment]
That's cool I've got a beta licence so was wondering if you would create a container, think it is still a bit early but should be good. Oh and good work with the docker containers love them and have 8 of yours running on my home server.
