### ISSUE TITLE
Dockerhub published as mcmyadmin2

### ISSUE THREAD

**Issue by krohrsb** [linuxserver/docker-mcmyadmin2#5]
Hello,

Readme mentions docker hub repo/image "linuxserver/mcmyadmin" however it is currently published under "linuxserver/mcmyadmin2" which is is a tad confusing.

Just FYI.

**Comment by lonix** [comment]
Yes, this stems to the fact that mcmyadmin2 and mcmyadmin3 are 2 diffrent products, and the seperation in names is there to specify the version for dockerhub, renameing the github repo, never seemd important. but I will make that said change now.
